import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  output: process.env.GITHUB_PAGES ? 'export' : undefined,
  basePath: process.env.GITHUB_PAGES ? '/refraction-ui' : '',
  images: { unoptimized: true },
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: true },
  transpilePackages: [
    '@refraction-ui/react',
    '@refraction-ui/react-app-shell',
    '@refraction-ui/app-shell',
    '@refraction-ui/react-theme',
    '@refraction-ui/react-avatar',
    '@refraction-ui/react-button',
    '@refraction-ui/react-card',
    '@refraction-ui/react-input',
    '@refraction-ui/react-dialog',
    '@refraction-ui/react-badge',
    '@refraction-ui/react-toast',
    '@refraction-ui/react-tabs',
    '@refraction-ui/react-animated-text',
    '@refraction-ui/react-auth',
    '@refraction-ui/react-bottom-nav',
    '@refraction-ui/react-breadcrumbs',
    '@refraction-ui/react-calendar',
    '@refraction-ui/react-charts',
    '@refraction-ui/react-code-editor',
    '@refraction-ui/react-collapsible',
    '@refraction-ui/react-command',
    '@refraction-ui/react-content-protection',
    '@refraction-ui/react-data-table',
    '@refraction-ui/react-device-frame',
    '@refraction-ui/react-dropdown-menu',
    '@refraction-ui/react-feedback-dialog',
    '@refraction-ui/react-footer',
    '@refraction-ui/react-inline-editor',
    '@refraction-ui/react-input-group',
    '@refraction-ui/react-install-prompt',
    '@refraction-ui/react-language-selector',
    '@refraction-ui/react-markdown-renderer',
    '@refraction-ui/react-mobile-nav',
    '@refraction-ui/react-navbar',
    '@refraction-ui/react-popover',
    '@refraction-ui/react-progress-display',
    '@refraction-ui/react-resizable-layout',
    '@refraction-ui/react-search-bar',
    '@refraction-ui/react-sidebar',
    '@refraction-ui/react-skeleton',
    '@refraction-ui/react-slide-viewer',
    '@refraction-ui/react-tabs',
    '@refraction-ui/react-textarea',
    '@refraction-ui/react-tooltip',
    '@refraction-ui/react-version-selector',
    '@refraction-ui/react-video-player',
    '@refraction-ui/tailwind-config',
    '@refraction-ui/shared',
    '@refraction-ui/avatar',
    '@refraction-ui/button',
    '@refraction-ui/card',
    '@refraction-ui/input',
    '@refraction-ui/dialog',
    '@refraction-ui/badge',
    '@refraction-ui/toast',
    '@refraction-ui/tabs',
    '@refraction-ui/theme',
  ],
}

export default nextConfig
