import 'package:flutter/widgets.dart';

/// The nine top-level Unicode emoji groups, in canonical order.
///
/// These are the *content* categories. UI affordances such as "recently
/// used" and "stickers" are surfaced as their own tabs by
/// [RefractionEmojiPicker] and are intentionally NOT members of this enum —
/// they are not part of the Unicode dataset.
enum EmojiCategory {
  smileys,
  people,
  nature,
  food,
  travel,
  activities,
  objects,
  symbols,
  flags,
}

/// A single emoji from the Unicode dataset.
///
/// This is the shape both [RefractionEmojiPicker] and the composer's
/// `refractionDefaultShortcodes()` consume, so the whole library shares one
/// source of truth (`lib/src/data/emoji_dataset.g.dart`, generated by
/// `tool/generate_emoji_data.dart`).
class EmojiEntry {
  /// The rendered glyph, e.g. `😀`.
  final String emoji;

  /// The canonical Unicode short name, e.g. `grinning face`.
  final String name;

  /// The Unicode group this emoji belongs to.
  final EmojiCategory category;

  /// Free-text search tags (may be empty). Used for fuzzy search only.
  final List<String> keywords;

  /// `:code:` aliases (at least one). The first is the canonical shortcode.
  final List<String> shortcodes;

  /// The Unicode version that introduced this emoji (e.g. `6.1`), if known.
  final String? unicodeVersion;

  /// Creates an emoji entry. [keywords]/[shortcodes] default to empty so the
  /// hand-written smoke fixtures and older call sites keep compiling.
  const EmojiEntry({
    required this.emoji,
    required this.name,
    required this.category,
    this.keywords = const [],
    this.shortcodes = const [],
    this.unicodeVersion,
  });

  /// The canonical `:shortcode:` slug (without the surrounding colons).
  ///
  /// Falls back to the snake-cased [name] when no alias exists so a
  /// shortcode always resolves.
  String get shortcode =>
      shortcodes.isNotEmpty ? shortcodes.first : name.replaceAll(' ', '_');

  /// All lower-cased terms this entry can be matched against.
  Iterable<String> get searchTerms sync* {
    yield name.toLowerCase();
    for (final s in shortcodes) {
      yield s.toLowerCase();
    }
    for (final k in keywords) {
      yield k.toLowerCase();
    }
  }
}

/// A host- or future-bundled sticker.
///
/// Stickers are deliberately empty by default: the maintainer decides
/// separately whether (and which) sticker assets to ship. A host can inject
/// its own via [RefractionEmojiPicker.stickers]; each sticker paints through
/// the same [EmojiRenderer] seam as emoji, so no picker changes are needed
/// when a set is added later.
class EmojiSticker {
  /// Stable identifier reported back on selection.
  final String id;

  /// Human-readable label (tooltip / accessible name).
  final String label;

  /// Search terms.
  final List<String> keywords;

  /// A glyph fallback used by the default renderer when [builder] is null.
  final String? glyph;

  /// Optional custom painter for this sticker (image/Lottie/etc.). When
  /// null, the picker paints [glyph] as text.
  final Widget Function(BuildContext context, double size)? builder;

  /// Creates a sticker descriptor.
  const EmojiSticker({
    required this.id,
    required this.label,
    this.keywords = const [],
    this.glyph,
    this.builder,
  });
}

/// The single seam for making emoji glyphs uniform across platforms.
///
/// Native emoji glyphs are NOT uniform across OSes/versions, and the library
/// deliberately does NOT bundle a font/image set (a licensing + bundle-size
/// decision left to the maintainer). Native rendering is the baseline; swap
/// in a uniform set (Noto / Fluent / Twemoji / Lottie) later by passing a
/// custom [EmojiRenderer] to [RefractionEmojiPicker] — with zero changes to
/// the dataset or the picker itself.
typedef EmojiRenderer =
    Widget Function(BuildContext context, EmojiEntry entry, double size);

/// The baseline [EmojiRenderer]: renders the native glyph as text.
Widget defaultEmojiRenderer(
  BuildContext context,
  EmojiEntry entry,
  double size,
) => Text(
  entry.emoji,
  style: TextStyle(fontSize: size, height: 1.0),
  textAlign: TextAlign.center,
);

/// Display metadata for the emoji categories (icons + labels).
class EmojiCategoryMeta {
  const EmojiCategoryMeta._();

  /// A representative glyph shown on each category tab.
  static const Map<EmojiCategory, String> icons = {
    EmojiCategory.smileys: '😀',
    EmojiCategory.people: '👋',
    EmojiCategory.nature: '🐶',
    EmojiCategory.food: '🍎',
    EmojiCategory.travel: '🚗',
    EmojiCategory.activities: '⚽',
    EmojiCategory.objects: '💡',
    EmojiCategory.symbols: '❤️',
    EmojiCategory.flags: '🏁',
  };

  /// Human-readable category names.
  static const Map<EmojiCategory, String> labels = {
    EmojiCategory.smileys: 'Smileys & Emotion',
    EmojiCategory.people: 'People & Body',
    EmojiCategory.nature: 'Animals & Nature',
    EmojiCategory.food: 'Food & Drink',
    EmojiCategory.travel: 'Travel & Places',
    EmojiCategory.activities: 'Activities',
    EmojiCategory.objects: 'Objects',
    EmojiCategory.symbols: 'Symbols',
    EmojiCategory.flags: 'Flags',
  };
}
