export { default as AnalyticsScript } from './AnalyticsScript.astro'

// Re-export core factories and types for convenience. The Astro adapter is a
// thin island over the neutral router — no privileged engine, every vendor is
// a sink, and the recommended prod topology routes through your server relay.
export {
  createAnalytics,
  createHttpSink,
  createConsoleSink,
  createMockSink,
  createSession,
  createIdentity,
  createConsent,
  createRedactor,
  createMemoryStorage,
  createLocalStorageAdapter,
  createCookieAdapter,
  resolveStorage,
  campaignFingerprint,
  uuidv4,
  isUuidV4,
  UUID_V4_RE,
  PII_DENY_LIST,
  PII_EXACT_KEYS,
  REDACTED,
  SCHEMA_VERSION,
  DEFAULT_SESSION_TIMEOUT_MS,
  type Analytics,
  type AnalyticsConfig,
  type AnalyticsEvent,
  type AnalyticsEventType,
  type AnalyticsProperties,
  type AnalyticsContext,
  type AnalyticsSink,
  type AnalyticsStorage,
  type SinkInitContext,
  type SinkDeliverContext,
  type SessionConfig,
  type SessionAPI,
  type IdentityConfig,
  type ConsentConfig,
  type ConsentAPI,
  type HttpSinkOptions,
  type CallOptions,
  type ConsoleSinkOptions,
  type MockSink,
  type CreateMockSinkOptions,
  type Redactor,
} from '@refraction-ui/analytics'
