import { test, expect } from '@playwright/test'

test('named adjacent actions preserve the editor draft and support keyboard menu use', async ({ page, isMobile }) => {
  await page.goto('/components/composer')
  const example = page.getByTestId('composer-toolbar-example')
  const editor = example.getByRole('textbox')
  const dictate = example.getByRole('button', { name: 'Dictate', exact: true })
  const language = example.getByRole('button', { name: 'Dictation language', exact: true })
  await editor.fill('Draft remains available\nfor review.')
  const draft = await editor.inputValue()
  await dictate.focus()
  await page.keyboard.press('Enter')
  await expect(example.getByRole('status')).toContainText('Dictate requested')
  await dictate.focus()
  await expect(dictate).toBeFocused()
  // The mobile browser's default Tab traversal skips native buttons.
  // Desktop proves sequential Tab access; both exercise native key activation.
  if (isMobile) await language.focus()
  else await page.keyboard.press('Tab')
  await expect(language).toBeFocused()
  await page.keyboard.press('Space')
  await expect(page.getByRole('menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(language).toBeFocused()
  await expect(editor).toHaveValue(draft)
  if (!isMobile) {
    await language.press('Enter')
    await expect(page.getByRole('menuitem', { name: 'Auto', exact: true })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(example.getByRole('button', { name: 'Send', exact: true })).toBeFocused()
    await expect(page.getByRole('menu')).not.toBeVisible()
    await language.press('Enter')
    await page.keyboard.press('Shift+Tab')
    await expect(dictate).toBeFocused()
    await expect(page.getByRole('menu')).not.toBeVisible()
    await expect(editor).toHaveValue(draft)
  }
  await language.press('Enter')
  await expect(page.getByRole('menuitem', { name: 'Auto', exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByRole('menuitem', { name: 'Telugu', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(language).toBeFocused()
  await expect(example.getByRole('status')).toContainText('Language: Telugu')
  await expect(editor).toHaveValue(draft)
  const boxes = await Promise.all([editor, dictate, language].map((locator) => locator.boundingBox()))
  const [field, mic, caret] = boxes
  expect(field && mic && caret).toBeTruthy()
  expect(mic!.y).toBeGreaterThanOrEqual(field!.y + field!.height)
  expect(caret!.x - (mic!.x + mic!.width)).toBeLessThanOrEqual(4)
  expect(Math.abs(mic!.y - caret!.y)).toBeLessThanOrEqual(1)
})
