export { default as VoicePill } from './VoicePill.astro'
export {
  createVoicePill,
  clampVoicePillIntensity,
  getVoicePillAriaLabel,
  getVoicePillInitials,
  getVoicePillPosition,
  getVoicePillPulseStyle,
  getVoicePillSpeakerKey,
  getVoicePillSpeakerLabel,
  type VoicePillAPI,
  type VoicePillPosition,
  type VoicePillProps as CoreVoicePillProps,
  type VoicePillSpeaker,
  type VoicePillStyleVars,
  voicePillAvatarStyles,
  voicePillAvatarWrapStyles,
  voicePillLabelStyles,
  voicePillMuteButtonStyles,
  voicePillPositionVariants,
  voicePillPulseRingStyles,
  voicePillRootStyles,
  voicePillSpeakerStyles,
  voicePillSubStyles,
  voicePillTextStyles,
  voicePillTokens,
} from '@refraction-ui/voice-pill'
