export {
  Waveform,
  type WaveformProps,
} from './waveform.js'

export {
  DEFAULT_WAVEFORM_BAR_COUNT,
  DEFAULT_WAVEFORM_COLOR,
  DEFAULT_WAVEFORM_HEIGHT,
  DEFAULT_WAVEFORM_INTENSITY,
  DEFAULT_WAVEFORM_SMOOTHING,
  createIntensitySamples,
  createSilentSamples,
  createWaveform,
  drawWaveform,
  getWaveformPeak,
  isWaveformSampleInput,
  normalizeBarCount,
  normalizeIntensity,
  normalizeSmoothing,
  normalizeWaveformConfig,
  normalizeWaveformSamples,
  prepareWaveformCanvas,
  resampleWaveformSamples,
  scaleWaveformSamples,
  smoothWaveformSamples,
  toCssDimension,
  waveformCanvasVariants,
  waveformVariants,
  type NormalizedWaveformConfig,
  type WaveformAPI,
  type WaveformCanvasSize,
  type WaveformProps as CoreWaveformProps,
  type WaveformRenderOptions,
  type WaveformSampleInput,
  type WaveformSource,
  type WaveformVariant,
} from '@refraction-ui/waveform'
