export { default as Waveform } from './Waveform.astro'
export {
  createIntensitySamples,
  createSilentSamples,
  createWaveform,
  drawWaveform,
  getWaveformPeak,
  isWaveformSampleInput,
  normalizeBarCount,
  normalizeIntensity,
  normalizeSmoothing,
  normalizeWaveformConfig,
  normalizeWaveformSamples,
  prepareWaveformCanvas,
  resampleWaveformSamples,
  scaleWaveformSamples,
  smoothWaveformSamples,
  toCssDimension,
  type NormalizedWaveformConfig,
  type WaveformAPI,
  type WaveformCanvasSize,
  type WaveformProps as CoreWaveformProps,
  type WaveformRenderOptions,
  type WaveformSampleInput,
  type WaveformSource,
  type WaveformVariant,
  waveformCanvasVariants,
  waveformVariants,
} from '@refraction-ui/waveform'
