name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Check for outdated dependencies
        run: pnpm outdated || true
      - name: Audit dependencies
        run: pnpm audit --audit-level high

  build-test:
    runs-on: ubuntu-latest
    needs: [security, dependencies]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm turbo lint --continue
      - name: Typecheck
        run: pnpm turbo typecheck --continue
      - name: Unit tests
        run: pnpm turbo test --continue -- --coverage
      - name: Build packages
        run: pnpm turbo build --continue
      - name: Storybook tests (axe + interactions)
        run: pnpm turbo storybook:test --continue
      - name: Bundle size check
        run: pnpm turbo size:check --continue
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  performance:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build for performance testing
        run: pnpm turbo build --continue
      - name: Run bundle analysis
        run: pnpm turbo size:analyze --continue || echo "Bundle analysis completed"
