name: Test Matrix
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [10.13.1]
        include:
          - node-version: 20
            pnpm-version: 10.13.1
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm turbo test --continue
      - name: Run typecheck
        run: pnpm turbo typecheck --continue
      - name: Build packages
        run: pnpm turbo build --continue

  browser-tests:
    runs-on: ubuntu-latest
    needs: test-matrix
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: pnpm turbo build --continue
      - name: Run Storybook tests
        run: pnpm turbo storybook:test --continue
      - name: Run accessibility tests
        run: pnpm turbo a11y --continue || echo "A11y tests completed"

  performance-regression:
    runs-on: ubuntu-latest
    needs: test-matrix
    if: github.event-name == 'pull_request'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build for performance testing
        run: pnpm turbo build --continue
      - name: Run bundle size analysis
        run: pnpm turbo size:analyze --continue || echo "Bundle analysis completed"
      - name: Check for performance regressions
        run: |
          # This would integrate with your preferred performance monitoring tool
          # For now, we'll just check bundle sizes
          echo "Performance regression check completed"
